# Generated by Django 6.0.5 on 2026-06-10 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=170, unique=True)),
                ('short_bio', models.CharField(blank=True, max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='artists/')),
                ('instagram_url', models.URLField(blank=True, max_length=500)),
                ('spotify_url', models.URLField(blank=True, max_length=500)),
                ('youtube_url', models.URLField(blank=True, max_length=500)),
                ('artist_type', models.CharField(choices=[('solo', 'Solo Artist'), ('band', 'Band'), ('dj', 'DJ'), ('other', 'Other')], default='band', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('feature_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['feature_order', 'name'],
                'indexes': [models.Index(fields=['is_active', 'name'], name='artists_art_is_acti_1a8da9_idx'), models.Index(fields=['is_featured', 'feature_order'], name='artists_art_is_feat_105170_idx')],
            },
        ),
    ]
