# Generated by Django 6.0.5 on 2026-06-10 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
        ('events', '0001_initial'),
        ('merch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_code', models.CharField(editable=False, max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('closed', 'Closed')], default='new', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('related_artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to='artists.artist')),
            ],
            options={
                'verbose_name': 'Artist enquiry',
                'verbose_name_plural': 'Artist enquiries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='enquiries_a_status_95cad5_idx'), models.Index(fields=['related_artist', 'status'], name='enquiries_a_related_345747_idx')],
            },
        ),
        migrations.CreateModel(
            name='EnquirySubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_code', models.CharField(editable=False, max_length=20, unique=True)),
                ('enquiry_type', models.CharField(choices=[('general', 'General'), ('merch', 'Merch'), ('studio', 'Studio'), ('venue', 'Venue')], max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('subject', models.CharField(max_length=200)),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('preferred_start_time', models.TimeField(blank=True, null=True)),
                ('amount_text', models.CharField(blank=True, max_length=100)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Requested quantity for merch enquiries.')),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('in_review', 'In Review'), ('replied', 'Replied'), ('closed', 'Closed')], default='new', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('related_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiry_submissions', to='events.event')),
                ('related_merch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiry_submissions', to='merch.merchitem')),
            ],
            options={
                'verbose_name': 'Enquiry submission',
                'verbose_name_plural': 'Enquiries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['enquiry_type', 'status'], name='enquiries_e_enquiry_1fc188_idx'), models.Index(fields=['status', 'created_at'], name='enquiries_e_status_01f014_idx')],
            },
        ),
    ]
