# Generated by Django 6.0.5 on 2026-05-22 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('merch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnquirySubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_code', models.CharField(editable=False, max_length=20, unique=True)),
                ('enquiry_type', models.CharField(choices=[('general', 'General'), ('merch', 'Merch'), ('payment', 'Payment')], max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('subject', models.CharField(max_length=200)),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('amount_text', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('in_review', 'In Review'), ('replied', 'Replied'), ('closed', 'Closed')], default='new', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('related_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiry_submissions', to='events.event')),
                ('related_merch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiry_submissions', to='merch.merchitem')),
            ],
            options={
                'verbose_name': 'Enquiry submission',
                'verbose_name_plural': 'Enquiries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['enquiry_type', 'status'], name='enquiries_e_enquiry_1fc188_idx'), models.Index(fields=['status', 'created_at'], name='enquiries_e_status_01f014_idx')],
            },
        ),
    ]
