# Generated by Django 6.0.5 on 2026-05-25 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
        ('enquiries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_code', models.CharField(editable=False, max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('time_start', models.TimeField(help_text='E.g., 2:00 PM')),
                ('time_end', models.TimeField(help_text='E.g., 4:00 PM')),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('closed', 'Closed')], default='new', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('related_artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to='artists.artist')),
            ],
            options={
                'verbose_name': 'Artist enquiry',
                'verbose_name_plural': 'Artist enquiries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='enquiries_a_status_95cad5_idx'), models.Index(fields=['related_artist', 'status'], name='enquiries_a_related_345747_idx')],
            },
        ),
    ]
