# Generated by Django 6.0.5 on 2026-05-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0002_artistenquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistenquiry',
            name='preferred_date',
            field=models.DateField(blank=True, help_text='Date when you would like to meet', null=True),
        ),
    ]
