# Generated by Django 6.0.5 on 2026-05-25 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0003_artistenquiry_preferred_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistenquiry',
            name='preferred_date',
        ),
        migrations.RemoveField(
            model_name='artistenquiry',
            name='time_end',
        ),
        migrations.RemoveField(
            model_name='artistenquiry',
            name='time_start',
        ),
    ]
