# Generated by Django 6.0.5 on 2026-05-25 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0004_remove_artistenquiry_preferred_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquirysubmission',
            name='preferred_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enquirysubmission',
            name='enquiry_type',
            field=models.CharField(choices=[('general', 'General'), ('merch', 'Merch'), ('payment', 'Payment'), ('studio', 'Studio'), ('venue', 'Venue')], max_length=20),
        ),
    ]
