# Generated by Django 6.0.5 on 2026-05-25 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0005_enquirysubmission_preferred_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquirysubmission',
            name='preferred_time',
        ),
        migrations.AddField(
            model_name='enquirysubmission',
            name='preferred_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
