# Generated by Django 6.0.5 on 2026-06-10 06:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Event category',
                'verbose_name_plural': 'Event categories',
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['is_active', 'sort_order'], name='events_even_is_acti_885ee4_idx')],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('short_description', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='events/posters/')),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('time_note', models.CharField(blank=True, help_text="Optional public-facing timing text, e.g. '10 PM until late' or '8 PM onwards'.", max_length=120)),
                ('location_text', models.CharField(blank=True, max_length=255)),
                ('ticket_url', models.URLField(blank=True)),
                ('price_text', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='events.eventcategory')),
            ],
            options={
                'ordering': ['start_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='MYR', max_length=3)),
                ('quantity_total', models.PositiveIntegerField(help_text='Total number of tickets available for this ticket type.', validators=[django.core.validators.MinValueValidator(1)])),
                ('quantity_sold', models.PositiveIntegerField(default=0, help_text='Reserved for future checkout/ticket issuing logic.')),
                ('sales_start_at', models.DateTimeField(blank=True, null=True)),
                ('sales_end_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_types', to='events.event')),
            ],
            options={
                'ordering': ['sort_order', 'price_amount', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EventArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role_name', models.CharField(blank=True, max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_links', to='artists.artist')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_artists', to='events.event')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'indexes': [models.Index(fields=['event', 'sort_order'], name='events_even_event_i_40b93a_idx'), models.Index(fields=['artist'], name='events_even_artist__1492b9_idx')],
                'constraints': [models.UniqueConstraint(fields=('event', 'artist'), name='unique_event_artist')],
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['status', 'start_at'], name='events_even_status_76ecd8_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['is_featured', 'start_at'], name='events_even_is_feat_39d568_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['category', 'start_at'], name='events_even_categor_188b18_idx'),
        ),
        migrations.AddIndex(
            model_name='tickettype',
            index=models.Index(fields=['event', 'is_active', 'sort_order'], name='events_tick_event_i_614678_idx'),
        ),
        migrations.AddIndex(
            model_name='tickettype',
            index=models.Index(fields=['sales_start_at', 'sales_end_at'], name='events_tick_sales_s_209f03_idx'),
        ),
        migrations.AddIndex(
            model_name='tickettype',
            index=models.Index(fields=['currency', 'price_amount'], name='events_tick_currenc_26d12d_idx'),
        ),
        migrations.AddConstraint(
            model_name='tickettype',
            constraint=models.UniqueConstraint(fields=('event', 'name'), name='unique_ticket_type_per_event'),
        ),
        migrations.AddConstraint(
            model_name='tickettype',
            constraint=models.CheckConstraint(condition=models.Q(('price_amount__gte', 0)), name='ticket_type_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='tickettype',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_total__gte', 1)), name='ticket_type_quantity_total_positive'),
        ),
        migrations.AddConstraint(
            model_name='tickettype',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_sold__gte', 0)), name='ticket_type_quantity_sold_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='tickettype',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_sold__lte', models.F('quantity_total'))), name='ticket_type_quantity_sold_lte_total'),
        ),
    ]
