# Generated by Django 6.0.5 on 2026-05-24 03:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='MYR', max_length=3)),
                ('quantity_total', models.PositiveIntegerField(help_text='Total number of tickets available for this ticket type.', validators=[django.core.validators.MinValueValidator(1)])),
                ('quantity_sold', models.PositiveIntegerField(default=0, help_text='Reserved for future checkout/ticket issuing logic.')),
                ('sales_start_at', models.DateTimeField(blank=True, null=True)),
                ('sales_end_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_types', to='events.event')),
            ],
            options={
                'ordering': ['sort_order', 'price_amount', 'name'],
                'indexes': [models.Index(fields=['event', 'is_active', 'sort_order'], name='events_tick_event_i_614678_idx'), models.Index(fields=['sales_start_at', 'sales_end_at'], name='events_tick_sales_s_209f03_idx'), models.Index(fields=['currency', 'price_amount'], name='events_tick_currenc_26d12d_idx')],
                'constraints': [models.UniqueConstraint(fields=('event', 'name'), name='unique_ticket_type_per_event'), models.CheckConstraint(condition=models.Q(('price_amount__gte', 0)), name='ticket_type_price_non_negative'), models.CheckConstraint(condition=models.Q(('quantity_total__gte', 1)), name='ticket_type_quantity_total_positive'), models.CheckConstraint(condition=models.Q(('quantity_sold__gte', 0)), name='ticket_type_quantity_sold_non_negative'), models.CheckConstraint(condition=models.Q(('quantity_sold__lte', models.F('quantity_total'))), name='ticket_type_quantity_sold_lte_total')],
            },
        ),
    ]
