# Generated by Django 6.0.5 on 2026-06-10 06:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('merch', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_code', models.CharField(blank=True, max_length=32, unique=True)),
                ('customer_name', models.CharField(max_length=150)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_payment', 'Pending Payment'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded')], default='draft', max_length=30)),
                ('currency', models.CharField(default='MYR', max_length=3)),
                ('subtotal_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('admin_notes', models.TextField(blank=True)),
                ('inventory_committed_at', models.DateTimeField(blank=True, editable=False, help_text='Set when stock/ticket inventory has been committed for this order.', null=True)),
                ('inventory_released_at', models.DateTimeField(blank=True, editable=False, help_text='Set when previously committed inventory has been released.', null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='orders_orde_status_25e057_idx'), models.Index(fields=['reference_code'], name='orders_orde_referen_1cc4b5_idx'), models.Index(fields=['customer_email'], name='orders_orde_custome_ca0107_idx'), models.Index(fields=['currency', 'total_amount'], name='orders_orde_currenc_94bed8_idx'), models.Index(fields=['status', 'inventory_committed_at'], name='orders_orde_status_8b42e3_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('subtotal_amount__gte', 0)), name='order_subtotal_amount_non_negative'), models.CheckConstraint(condition=models.Q(('discount_amount__gte', 0)), name='order_discount_amount_non_negative'), models.CheckConstraint(condition=models.Q(('tax_amount__gte', 0)), name='order_tax_amount_non_negative'), models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='order_total_amount_non_negative')],
            },
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('status_changed', 'Status Changed'), ('inventory_committed', 'Inventory Committed'), ('inventory_released', 'Inventory Released'), ('email_sent', 'Email Sent'), ('email_skipped', 'Email Skipped'), ('note', 'Note'), ('error', 'Error')], max_length=40)),
                ('from_status', models.CharField(blank=True, choices=[('draft', 'Draft'), ('pending_payment', 'Pending Payment'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded')], max_length=30)),
                ('to_status', models.CharField(blank=True, choices=[('draft', 'Draft'), ('pending_payment', 'Pending Payment'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded')], max_length=30)),
                ('message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Structured audit metadata for future payment/webhook events.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_history_entries', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='orders.order')),
            ],
            options={
                'verbose_name': 'Order history',
                'verbose_name_plural': 'Order history',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['order', 'created_at'], name='orders_orde_order_i_54a3d5_idx'), models.Index(fields=['event_type', 'created_at'], name='orders_orde_event_t_289c0b_idx'), models.Index(fields=['from_status', 'to_status'], name='orders_orde_from_st_fc3718_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('merch_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='merch.merchitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('ticket_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='events.tickettype')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['order'], name='orders_orde_order_i_5d347b_idx'), models.Index(fields=['merch_item'], name='orders_orde_merch_i_2b5da3_idx'), models.Index(fields=['ticket_type'], name='orders_orde_ticket__07d21b_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='order_item_quantity_positive'), models.CheckConstraint(condition=models.Q(('unit_amount__gte', 0)), name='order_item_unit_amount_non_negative'), models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='order_item_total_amount_non_negative'), models.CheckConstraint(condition=models.Q(models.Q(('merch_item__isnull', False), ('ticket_type__isnull', True)), models.Q(('merch_item__isnull', True), ('ticket_type__isnull', False)), _connector='OR'), name='order_item_exactly_one_sellable_item')],
            },
        ),
        migrations.CreateModel(
            name='PaymentProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(help_text='Upload a proof of payment (receipt, screenshot, etc.)', upload_to='payment_proofs/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'], message='Only PDF, JPG, and PNG files are allowed.')])),
                ('file_type', models.CharField(choices=[('image', 'Image (JPG, PNG)'), ('pdf', 'PDF Document')], max_length=20)),
                ('original_filename', models.CharField(blank=True, help_text='Original filename for reference', max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about the payment proof')),
                ('verified', models.BooleanField(default=False, help_text='Whether admin has verified this payment proof')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_proof', to='orders.order')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payment_proofs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Proof',
                'verbose_name_plural': 'Payment Proofs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order'], name='orders_paym_order_i_8141b0_idx'), models.Index(fields=['verified', 'created_at'], name='orders_paym_verifie_e8f16f_idx')],
            },
        ),
    ]
