# Generated by Django 6.0.5 on 2026-05-24 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='inventory_committed_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='Set when stock/ticket inventory has been committed for this order.', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='inventory_released_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='Set when previously committed inventory has been released.', null=True),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'inventory_committed_at'], name='orders_orde_status_8b42e3_idx'),
        ),
    ]
