# Generated by Django 6.0.5 on 2026-05-24 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_inventory_committed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('status_changed', 'Status Changed'), ('inventory_committed', 'Inventory Committed'), ('inventory_released', 'Inventory Released'), ('email_sent', 'Email Sent'), ('email_skipped', 'Email Skipped'), ('note', 'Note'), ('error', 'Error')], max_length=40)),
                ('from_status', models.CharField(blank=True, choices=[('draft', 'Draft'), ('pending_payment', 'Pending Payment'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded')], max_length=30)),
                ('to_status', models.CharField(blank=True, choices=[('draft', 'Draft'), ('pending_payment', 'Pending Payment'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded')], max_length=30)),
                ('message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Structured audit metadata for future payment/webhook events.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_history_entries', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='orders.order')),
            ],
            options={
                'verbose_name': 'Order history',
                'verbose_name_plural': 'Order history',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['order', 'created_at'], name='orders_orde_order_i_54a3d5_idx'), models.Index(fields=['event_type', 'created_at'], name='orders_orde_event_t_289c0b_idx'), models.Index(fields=['from_status', 'to_status'], name='orders_orde_from_st_fc3718_idx')],
            },
        ),
    ]
