# Generated by Django 6.0.5 on 2026-05-26 16:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(help_text='Upload a proof of payment (receipt, screenshot, etc.)', upload_to='payment_proofs/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'], message='Only PDF, JPG, and PNG files are allowed.')])),
                ('file_type', models.CharField(choices=[('image', 'Image (JPG, PNG)'), ('pdf', 'PDF Document')], max_length=20)),
                ('original_filename', models.CharField(blank=True, help_text='Original filename for reference', max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about the payment proof')),
                ('verified', models.BooleanField(default=False, help_text='Whether admin has verified this payment proof')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_proof', to='orders.order')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payment_proofs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Proof',
                'verbose_name_plural': 'Payment Proofs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order'], name='orders_paym_order_i_8141b0_idx'), models.Index(fields=['verified', 'created_at'], name='orders_paym_verifie_e8f16f_idx')],
            },
        ),
    ]
