# Generated by Django 6.0.5 on 2026-05-22 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MerchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('short_description', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='merch/items/')),
                ('price_text', models.CharField(blank=True, max_length=100)),
                ('availability_text', models.CharField(blank=True, help_text="Optional text like 'Limited stock', 'Pre-order', or 'Sold out'.", max_length=120)),
                ('cta_text', models.CharField(blank=True, max_length=50)),
                ('cta_url', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Merch item',
                'verbose_name_plural': 'Merch',
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['is_active', 'display_order'], name='merch_merch_is_acti_fd8441_idx'), models.Index(fields=['is_featured', 'display_order'], name='merch_merch_is_feat_79b57a_idx')],
            },
        ),
    ]
