# Generated by Django 6.0.5 on 2026-05-23 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='merchitem',
            options={'ordering': ['display_order', 'name'], 'verbose_name': 'Merchandise', 'verbose_name_plural': 'Merchandise'},
        ),
    ]
