# Generated by Django 6.0.5 on 2026-05-24 03:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0002_alter_merchitem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchitem',
            name='currency',
            field=models.CharField(default='MYR', max_length=3),
        ),
        migrations.AddField(
            model_name='merchitem',
            name='price_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Numeric price used for future checkout calculations.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='merchitem',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Current available stock when stock tracking is enabled.'),
        ),
        migrations.AddField(
            model_name='merchitem',
            name='track_stock',
            field=models.BooleanField(default=False, help_text='Enable if stock quantity should be tracked.'),
        ),
        migrations.AddIndex(
            model_name='merchitem',
            index=models.Index(fields=['currency', 'price_amount'], name='merch_merch_currenc_4ff473_idx'),
        ),
        migrations.AddConstraint(
            model_name='merchitem',
            constraint=models.CheckConstraint(condition=models.Q(('price_amount__gte', 0)), name='merch_price_amount_non_negative'),
        ),
    ]
