# Generated by Django 6.0.5 on 2026-06-10 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site_name', models.CharField(max_length=150)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('address_text', models.TextField(blank=True)),
                ('google_maps_url', models.URLField(blank=True, max_length=500)),
                ('instagram_url', models.URLField(blank=True, max_length=500)),
                ('facebook_url', models.URLField(blank=True, max_length=500)),
                ('tiktok_url', models.URLField(blank=True, max_length=500)),
                ('youtube_url', models.URLField(blank=True, max_length=500)),
                ('whatsapp_url', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page_key', models.CharField(choices=[('home', 'Home'), ('about', 'About'), ('contact', 'Contact'), ('studio', 'Studio'), ('events', 'Events')], max_length=20)),
                ('section_key', models.SlugField()),
                ('title', models.CharField(blank=True, max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='pages/sections/')),
                ('cta_text', models.CharField(blank=True, max_length=100)),
                ('cta_url', models.URLField(blank=True, max_length=500)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['page_key', 'sort_order', 'id'],
                'indexes': [models.Index(fields=['page_key', 'is_active', 'sort_order'], name='pages_pages_page_ke_e80269_idx')],
                'constraints': [models.UniqueConstraint(fields=('page_key', 'section_key'), name='unique_page_section_key')],
            },
        ),
    ]
