# Generated by Django 6.0.5 on 2026-06-10 09:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_code', models.CharField(blank=True, max_length=32, unique=True)),
                ('request_type', models.CharField(choices=[('general', 'General'), ('studio', 'Studio'), ('venue', 'Venue')], max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('preferred_start_time', models.TimeField(blank=True, null=True)),
                ('preferred_end_time', models.TimeField(blank=True, null=True)),
                ('guest_count', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('in_review', 'In Review'), ('contacted', 'Contacted'), ('converted', 'Booking Created'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='new', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_requests', to='events.event')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleCalendar',
            fields=[
            ],
            options={
                'verbose_name': 'Admin Calendar',
                'verbose_name_plural': 'Admin Calendar',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('bookings.bookingrequest',),
        ),
        migrations.CreateModel(
            name='BookingResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=170, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['is_active', 'display_order'], name='bookings_bo_is_acti_4488fe_idx')],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_code', models.CharField(blank=True, max_length=32, unique=True)),
                ('booking_type', models.CharField(choices=[('studio', 'Studio'), ('venue', 'Venue')], max_length=30)),
                ('title', models.CharField(blank=True, help_text='Optional internal title. If blank, the linked request name is used.', max_length=200)),
                ('scheduled_start_at', models.DateTimeField()),
                ('scheduled_end_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('tentative', 'Tentative'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('no_show', 'No Show')], default='tentative', max_length=30)),
                ('internal_notes', models.TextField(blank=True)),
                ('request', models.ForeignKey(blank=True, help_text='Optional. Link this booking to the original public request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='bookings.bookingrequest')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='bookings.bookingresource')),
            ],
            options={
                'ordering': ['scheduled_start_at', 'title', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='bookingrequest',
            index=models.Index(fields=['status', 'created_at'], name='bookings_bo_status_a25b66_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingrequest',
            index=models.Index(fields=['request_type', 'created_at'], name='bookings_bo_request_56be17_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingrequest',
            index=models.Index(fields=['event'], name='bookings_bo_event_i_ecba61_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingrequest',
            index=models.Index(fields=['reference_code'], name='bookings_bo_referen_451074_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'scheduled_start_at'], name='bookings_bo_status_834e01_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'scheduled_end_at'], name='bookings_bo_status_9d2f7a_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['resource', 'status', 'scheduled_start_at'], name='bookings_bo_resourc_861fc8_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_type', 'status', 'scheduled_start_at'], name='bookings_bo_booking_8974ca_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['request'], name='bookings_bo_request_e73d81_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['reference_code'], name='bookings_bo_referen_543fdb_idx'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('scheduled_end_at__gt', models.F('scheduled_start_at'))), name='booking_scheduled_end_after_start'),
        ),
    ]
