# Generated by Django 6.0.5 on 2026-05-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='scheduled_end_at',
            field=models.DateTimeField(blank=True, help_text='Confirmed internal end time. Used for the schedule calendar.', null=True),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='scheduled_start_at',
            field=models.DateTimeField(blank=True, help_text='Confirmed internal start time. Used for the schedule calendar.', null=True),
        ),
    ]
