# Generated by ProjectCero Phase 15 duplicate migration fix

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    # The preferred_start_time and preferred_end_time fields are already present
    # in 0001_initial.py in this local branch. Keeping this migration as a no-op
    # preserves the migration name while preventing duplicate-column errors when
    # creating a fresh test database.
    operations = []
