# Generated by Django 6.0.5 on 2026-05-23 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_bookingrequest_scheduled_end_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleCalendar',
            fields=[
            ],
            options={
                'verbose_name': 'Admin Calendar',
                'verbose_name_plural': 'Admin Calendar',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('bookings.bookingrequest',),
        ),
    ]
