# Generated by Django 6.0.5 on 2026-05-24 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_schedulecalendar'),
        ('events', '0001_initial'),
        ('studio', '0002_remove_studioservicecategory_studio_stud_is_acti_61f71f_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='studio_service',
            field=models.ForeignKey(blank=True, help_text='Optional. The studio service selected from the public studio page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_requests', to='studio.studioservice'),
        ),
        migrations.AddIndex(
            model_name='bookingrequest',
            index=models.Index(fields=['studio_service'], name='bookings_bo_studio__810654_idx'),
        ),
    ]
