# Generated by Django 6.0.5 on 2026-05-24 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_bookingrequest_studio_service_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_code', models.CharField(blank=True, max_length=32, unique=True)),
                ('booking_type', models.CharField(choices=[('studio', 'Studio'), ('venue', 'Venue')], max_length=30)),
                ('title', models.CharField(blank=True, help_text='Optional internal title. If blank, the linked request name is used.', max_length=200)),
                ('scheduled_start_at', models.DateTimeField()),
                ('scheduled_end_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('tentative', 'Tentative'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('no_show', 'No Show')], default='tentative', max_length=30)),
                ('internal_notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['scheduled_start_at', 'title', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BookingResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=170, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.RemoveIndex(
            model_name='bookingrequest',
            name='bookings_bo_studio__810654_idx',
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='request_type',
            field=models.CharField(choices=[('general', 'General'), ('studio', 'Studio'), ('venue', 'Venue')], max_length=20),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='scheduled_end_at',
            field=models.DateTimeField(blank=True, help_text='Legacy field. Use Booking scheduled end time instead.', null=True),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='scheduled_start_at',
            field=models.DateTimeField(blank=True, help_text='Legacy field. Use Booking scheduled start time instead.', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='request',
            field=models.ForeignKey(blank=True, help_text='Optional. Link this booking to the original public request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='bookings.bookingrequest'),
        ),
        migrations.AddIndex(
            model_name='bookingresource',
            index=models.Index(fields=['is_active', 'display_order'], name='bookings_bo_is_acti_4488fe_idx'),
        ),
        migrations.AddField(
            model_name='booking',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='bookings.bookingresource'),
        ),
        migrations.RemoveField(
            model_name='bookingrequest',
            name='studio_service',
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'scheduled_start_at'], name='bookings_bo_status_834e01_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'scheduled_end_at'], name='bookings_bo_status_9d2f7a_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['resource', 'status', 'scheduled_start_at'], name='bookings_bo_resourc_861fc8_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_type', 'status', 'scheduled_start_at'], name='bookings_bo_booking_8974ca_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['request'], name='bookings_bo_request_e73d81_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['reference_code'], name='bookings_bo_referen_543fdb_idx'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('scheduled_end_at__gt', models.F('scheduled_start_at'))), name='booking_scheduled_end_after_start'),
        ),
    ]
