# Generated by Django 6.0.5 on 2026-05-24 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_migrate_legacy_booking_requests_to_bookings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingrequest',
            name='scheduled_end_at',
        ),
        migrations.RemoveField(
            model_name='bookingrequest',
            name='scheduled_start_at',
        ),
    ]
