# Generated by Django 6.0.5 on 2026-05-25 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_remove_bookingrequest_scheduled_end_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='preferred_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
