# Generated by Django 6.0.5 on 2026-05-21 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudioServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Studio category',
                'verbose_name_plural': 'Studio categories',
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['is_active', 'sort_order'], name='studio_stud_is_acti_61f71f_idx')],
            },
        ),
        migrations.CreateModel(
            name='StudioService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=170, unique=True)),
                ('short_description', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='studio/services/')),
                ('price_text', models.CharField(blank=True, max_length=100)),
                ('duration_text', models.CharField(blank=True, max_length=100)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='studio.studioservicecategory')),
            ],
            options={
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['is_active', 'display_order'], name='studio_stud_is_acti_f96523_idx'), models.Index(fields=['is_featured', 'display_order'], name='studio_stud_is_feat_9c7189_idx'), models.Index(fields=['category', 'display_order'], name='studio_stud_categor_acd3d7_idx')],
            },
        ),
    ]
