# Generated by Django 6.0.5 on 2026-05-23 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='studioservicecategory',
            name='studio_stud_is_acti_61f71f_idx',
        ),
        migrations.RemoveIndex(
            model_name='studioservice',
            name='studio_stud_categor_acd3d7_idx',
        ),
        migrations.RemoveField(
            model_name='studioservice',
            name='category',
        ),
        migrations.DeleteModel(
            name='StudioServiceCategory',
        ),
    ]
