# Generated by Django 6.0.5 on 2026-05-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_remove_studioservicecategory_studio_stud_is_acti_61f71f_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Equipment',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active', 'name'], name='studio_equi_is_acti_0a3b32_idx')],
            },
        ),
    ]
